#!/usr/bin/env bash

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

# Fail when piped commands fail.
set -o pipefail

APP_ARGS="$*"
readonly APP_ARGS

is_litestream_enabled() {
  local IS_ENABLED='false'

  if [[ -n "${LITESTREAM_BUCKET:-}" ]]; then
    IS_ENABLED='true';
  fi

  echo "${IS_ENABLED}"
}

IS_LITESTREAM_ENABLED="$(is_litestream_enabled)"
readonly IS_LITESTREAM_ENABLED

# Echo commands to stdout.
set -x

APP_LAUNCH_CMD="/app/screenjournal -db ${DB_PATH} ${APP_ARGS}"

if [[ "${IS_LITESTREAM_ENABLED}" == 'true' ]]; then
  /app/litestream version
  echo "LITESTREAM_BUCKET=${LITESTREAM_BUCKET}"
  echo "LITESTREAM_ENDPOINT=${LITESTREAM_ENDPOINT:-}"

  if [[ -f "$DB_PATH" ]]; then
    echo "Existing database is $(stat -c %s "${DB_PATH}") bytes"
  else
    echo "No existing database found"
    # Restore database from remote storage.
    mkdir -p "$(dirname "${DB_PATH}")"
    /app/litestream restore -if-replica-exists "${DB_PATH}"
  fi

  # Let Litestream start screenjournal as a child process
  /app/litestream replicate -exec "$APP_LAUNCH_CMD"
else
  echo "Starting without litestream"
  eval "${APP_LAUNCH_CMD}"
fi
