app = "screenjournal"

kill_signal = "SIGINT"
kill_timeout = 30

[build.args]
  TZ = "America/New_York"

[env]
  PORT = "8080"
  SJ_BEHIND_PROXY = "yes"
  SJ_SMTP_HOST = "in.smtp.sendamatic.net"
  SJ_SMTP_PORT = "587"
  SJ_BASE_URL = "https://thescreenjournal.com"
  LITESTREAM_BUCKET="screenjournal-litestream"
  LITESTREAM_ENDPOINT="s3.us-west-002.backblazeb2.com"
  TZ = "America/New_York"

[deploy]
  strategy = "rolling"
  max_unavailable = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/about"

  [http_service.checks.headers]
    X-Forwarded-Proto = "https"
