#!/usr/bin/env bash

# Exit script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

pnpm exec prettier --check .
mapfile -t frontend_files < <(git ls-files -- '*.js' 'handlers/templates/**/*.html')
pnpm exec eslint --no-warn-ignored "${frontend_files[@]}"
