#!/usr/bin/env bash

# Exit script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

pnpm exec prettier --check .
pnpm exec eslint ./**/*.js
