#!/bin/bash

# Populate database with test data

sqlite3 data/store.db <<EOF
INSERT INTO users (
    username,
    is_admin,
    email,
    password_hash,
    created_time,
    last_modified_time
) VALUES (
    "mike",
    1,
    "mike@example.com",
    "\$2a\$10\$J5zqqeQgH80ScyOSeCNCD.1V3ApJ1ULYMwMEhOjG6j4SM1mqL84YO", -- Hash of "password"
    "2022-09-25T00:00:00-05:00",
    "2022-10-29T00:00:00-05:00"
);

INSERT INTO movies (
    tmdb_id,
    imdb_id,
    title,
    release_date
) VALUES (
    320588,
    "tt3766394",
    "Hello, My Name Is Doris",
    "2015-11-27T00:00:00Z"
),
(
    401847,
    "tt4595882",
    "Can You Ever Forgive Me?",
    "2018-10-19T00:00:00Z"
),
(
    604031,
    "tt8855960",
    "Straight Up",
    "2020-02-28T00:00:00Z"
),
(
    1003180,
    "tt21340412",
    "Inside the Mind of a Cat",
    "2022-08-18T00:00:00Z"
),
(
    644495,
    "tt11214590",
    "House of Gucci",
    "2021-11-24T00:00:00Z"
),
(
    12096,
    "tt0383216",
    "The Pink Panther",
    "2006-02-10T00:00:00Z"
),
(
    15159,
    "tt0838232",
    "The Pink Panther 2",
    "2009-02-06T00:00:00Z"
),
(
    10144,
    "tt0097757",
    "The Little Mermaid",
    "1989-11-17T00:00:00Z"
),
(
    826942,
    "tt14596320",
    "Spin Me Round",
    "2022-08-19T00:00:00Z"
),
(
    352695,
    "tt4661798",
    "Joshy",
    "2016-08-12T00:00:00Z"
),
(
    411873,
    "tt5666304",
    "The Little Hours",
    "2017-06-30T00:00:00Z"
);

INSERT INTO reviews (
  review_owner,
  movie_id,
  rating,
  blurb,
  watched_date,
  created_time,
  last_modified_time
) VALUES (
  "mike",
  1,
  5,
  "Great first half. Second half fell apart.",
  "2022-08-21T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  2,
  6,
  "",
  "2022-09-03T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  3,
  8,
  "Very sweet and original ",
  "2022-09-11T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  4,
  6,
  "Not much useful information, but fun to see cute cat videos while you pretend to learn something.",
  "2022-09-18T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  5,
  5,
  "Well-made, but not enough story for 2.5 hours.",
  "2022-09-25T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  6,
  8,
  "Silly fun, reminded me a lot of Naked Gun",
  "2022-10-02T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  7,
  3,
  "A small amount of the charm from the original, but it just has classic sequel problems of trying to recycle what worked from the original while adding lots of extraneous celebrities",
  "2022-10-08T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  8,
  6,
  "Fun music and animation, but because it's such a classic, the story is really predictable and not that fun to follow. Scuttle's jokes hold up 30 years later.",
  "2022-10-09T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  9,
  7,
  "It definitely kept me on my toes. I felt like it didn't hold together quite as much as I want, but I enjoyed the cast and the comedy.",
  "2022-10-16T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  10,
  7,
  "It had its ups and downs, but there were a lot of good jokes, good cast, original story.",
  "2022-10-23T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
),
(
  "mike",
  11,
  5,
  "Great cast. It had a lot of non sequiturs, so I'm wondering if it would have made more sense if I'd read The Decameron. Mostly enjoyed it, but it kind of goes off the rails by the end.",
  "2022-10-27T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00",
  "2022-10-29T00:00:00-05:00"
);
EOF
