#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

curl http://localhost:4001/api/debug/db/populate-dummy-data
