#!/usr/bin/env bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

DOCKER_BUILDKIT=1 \
  docker build -t screenjournal .

docker rm -f screenjournal || true

docker run \
  --env "PORT=4003" \
  --env "SJ_SMTP_HOST=${SJ_SMTP_HOST}" \
  --env "SJ_SMTP_PORT=${SJ_SMTP_PORT}" \
  --env "SJ_SMTP_USERNAME=${SJ_SMTP_USERNAME}" \
  --env "SJ_SMTP_PASSWORD=${SJ_SMTP_PASSWORD}" \
  --env "LITESTREAM_BUCKET=${LITESTREAM_BUCKET}" \
  --env "LITESTREAM_ENDPOINT=${LITESTREAM_ENDPOINT}" \
  --env "LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}" \
  --env "LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}" \
  --publish "0.0.0.0:4003:4003" \
  --name screenjournal \
  screenjournal
